import type { ListDataTypes } from '../types'

export const listData: ListDataTypes[] = [
  {
    id: 'p1',
    name: 'Ravi Traders',
    address: '12A Industrial Road',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700001',
    mobile: 9876543210,
    alternateMobile: 9876500000,
    isSupplier: 'yes',
    duePaymentReminder: '1st of every month',
    paymentDetails: [
      { date: '2025-05-01', paymentAmount: 5000 },
      { date: '2025-05-15', paymentAmount: 2500 },
    ],
    totalAmount: 10000,
    dueAmount: 2500,
    partyId: '',
    type: 'purchase',
    date: '',
    productItems: [],
    paymentHistory: [],
    paid: 0,
    due: 0,
  },
  {
    id: 'p2',
    name: 'Anil Constructions',
    address: '78B MG Road',
    city: 'Patna',
    state: 'Bihar',
    pincode: '800001',
    mobile: 9812345678,
    isSupplier: 'no',
    duePaymentReminder: '15th of every month',
    paymentDetails: [{ date: '2025-04-20', paymentAmount: 8000 }],
    totalAmount: 8000,
    dueAmount: 0,
    partyId: '',
    alternateMobile: 0,
    type: 'purchase',
    date: '',
    productItems: [],
    paymentHistory: [],
    paid: 0,
    due: 0,
  },
  {
    id: 'p3',
    name: 'Sharma Hardware',
    address: '45 Market Lane',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226001',
    mobile: 9922334455,
    alternateMobile: 9988776655,
    isSupplier: 'both',
    duePaymentReminder: 'Every Monday',
    paymentDetails: [
      { date: '2025-05-05', paymentAmount: 2000 },
      { date: '2025-05-12', paymentAmount: 2000 },
    ],
    totalAmount: 7000,
    dueAmount: 3000,
    partyId: '',
    type: 'purchase',
    date: '',
    productItems: [],
    paymentHistory: [],
    paid: 0,
    due: 0,
  },
  {
    id: 'p4',
    name: 'Elegant Interiors',
    address: '5 Park Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    mobile: 9876501234,
    isSupplier: 'no',
    duePaymentReminder: 'Every 10th day',
    paymentDetails: [{ date: '2025-03-10', paymentAmount: 15000 }],
    totalAmount: 20000,
    dueAmount: 5000,
    partyId: '',
    alternateMobile: 0,
    type: 'purchase',
    date: '',
    productItems: [],
    paymentHistory: [],
    paid: 0,
    due: 0,
  },
  {
    id: 'p5',
    name: 'Patel Building Supplies',
    address: '20 Station Road',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380001',
    mobile: 9090909090,
    isSupplier: 'yes',
    duePaymentReminder: 'Weekly on Friday',
    paymentDetails: [{ date: '2025-05-03', paymentAmount: 12000 }],
    totalAmount: 15000,
    dueAmount: 3000,
    partyId: '',
    alternateMobile: 0,
    type: 'purchase',
    date: '',
    productItems: [],
    paymentHistory: [],
    paid: 0,
    due: 0,
  },
]
